TailorFlow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('',include('apps.tailors.urls')),
    path('',include('apps.customers.urls')),
    path('',include('apps.orders.urls')),
    path('',include('apps.products.urls')),
    path('',include('apps.dashboard.urls')),
    path('',include('apps.transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/orders/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('orders/',views.orders,name='orders'),
    path('select-customer/',views.select_customer,name='select-customer'),
    path('select-products/<int:customer_id>/',views.select_products,name='select-products'),
    path('checkout/<int:customer_id>/',views.checkout,name='checkout'),
    path('order-details/<int:order_id>/',views.order_details,name='order-details'),
    path('api/filter-orders/',views.filter_orders,name='filter-orders'),
    path('generate-invoice-pdf/<int:order_id>/',views.generate_invoice_pdf,name='generate-invoice-pdf')
]

apps/orders/models.py
from django.db import models
from apps.customers.models import Customer
from apps.tailors.models import TailorUser
from apps.products.models import Product
from django.db.models.signals import pre_save
from django.dispatch import receiver
import datetime
# Create your models here.
class Order(models.Model):
    payment_choices = [
        ('PRE','PREPAID'),
        ('POST','POSTPAID')
    ]
    id = models.CharField(max_length=100,primary_key=True,unique=True,blank=True)
    tailor = models.ForeignKey(TailorUser,on_delete=models.CASCADE,null=True,blank=True)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE,null=True,blank=True)
    order_date_time = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    total_price = models.FloatField(blank=True,null=True)
    payment_type = models.CharField(max_length=50,choices=payment_choices,null=True)
    items_count = models.IntegerField(blank=True,null=True)
    
    class Meta:
        ordering = ['-order_date_time']



class OrderItem(models.Model):
    status_choices=[
        ('Not-Stitched','Not-Stitched'),
        ('Stitching','Stitching'),
        ('Delivered','Delivered'),
        ('Stitched',"Stitched")
    ]
    order = models.ForeignKey(Order,on_delete=models.CASCADE,blank=True,null=True,related_name='items')
    product = models.ForeignKey(Product,on_delete=models.DO_NOTHING,null=True)
    notes = models.TextField(max_length=200,blank=True,null=True)
    quantity = models.PositiveIntegerField(default=1)
    requested_date = models.DateField()
    status = models.CharField(max_length=100,choices=status_choices,default="Not-Stitched",blank=True,null=True)
    urgent = models.BooleanField(default=False,blank=True)
    stitched_on = models.DateField(blank=True,null=True)
    delivered_on = models.DateField(blank=True,null=True)
    class Meta:
        ordering = ['requested_date']

apps/orders/forms.py
from django import forms
from .models import Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

apps/orders/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404
from .forms import OrderForm
from apps.customers.models import Customer
from apps.products.models import Product
from apps.transactions.models import Transaction
from apps.transactions.forms import TransactionForm
from .models import Order, OrderItem
from django.forms import modelformset_factory
from django.contrib.auth.decorators import login_required
from django import forms
from django.db.models import Q
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.core import serializers
from datetime import datetime
from django.http import HttpResponse
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from io import BytesIO
from PIL import Image
import requests
from django.conf import settings
import urllib.parse
import os
# Create your views here.

@login_required
def orders(request):
    orders = Order.objects.filter(tailor=request.user)
    paginator = Paginator(orders, 5)
    page_obj = paginator.get_page(1)
    return render(request,'orders/orders.html',{'page_obj':page_obj,'title':'Orders'})

@login_required
def select_customer(request):
    customers = Customer.objects.filter(tailor=request.user)
    pagination = Paginator(customers,7)
    page_obj = pagination.get_page(1)
    return render(request,'orders/select_customer.html',context={'page_obj':page_obj})

@login_required
def select_products(request,customer_id):
    products = Product.objects.filter(tailor=request.user)
    return render(request,'orders/select_products.html',context={'products':products,'customer_id':customer_id})

@login_required
def checkout(request,customer_id):
    customer = Customer.objects.get(id=customer_id)
    print(customer_id)
    if request.method == 'POST':
        selected_product_ids = request.POST.getlist('selected_products')
        selected_products = Product.objects.filter(tailor=request.user,id__in=selected_product_ids)
        checkout_origin = request.POST.get('checkout','')
        OrderItemFormSet = modelformset_factory(OrderItem,fields='__all__',extra=len(selected_products))
        transaction_form = TransactionForm()
        if checkout_origin == 'true': 
            amount = int(request.POST.get('amount'))
            order_form = OrderForm(request.POST)
            formset = OrderItemFormSet(request.POST)
            transaction_form = TransactionForm(request.POST)
            # print(order_form)
            
            if order_form.is_valid() and formset.is_valid() and transaction_form.is_valid():
                order = order_form.save(commit=False)
                order.save()
                instances = formset.save(commit=False)
                for instance in instances:
                    instance.order = order
                    instance.save()
                if amount > 0:
                    transaction = transaction_form.save(commit=False)
                    transaction.order = order
                    transaction.save()
                return redirect('/orders')
            else:
                print(order_form.errors)
        else:
            order_id = generate_order_id(customer_id)
            order_form = OrderForm(initial={'tailor':request.user,'customer':customer,'items_count':len(selected_product_ids),'id':order_id})
            formset = OrderItemFormSet(queryset=OrderItem.objects.none(),initial=[{'product':product} for product in selected_products])
            return render(request,'orders/checkout.html',{
                'selected_products':selected_products,
                'customer':customer,
                'formset' : formset,
                'order_form':order_form,
                'transaction_form':transaction_form,
            })
    else:
        print("it's a get method")
        
def generate_order_id(customer_id):
    timestamp = datetime.now().strftime("%y%m%d%H%M%S")
    order_id = f"{timestamp}{customer_id}"
    return order_id

@login_required      
def order_details(request,order_id):
    order = get_object_or_404(Order, id=order_id)
    order_items = OrderItem.objects.filter(order=order)

    OrderItemFormSet = modelformset_factory(OrderItem,fields='__all__',extra=0)
    transaction_form = TransactionForm()
    transactions = Transaction.objects.filter(order=order)
    amount_paid = 0
    for transaction in transactions:
        amount_paid += transaction.amount

    max_input_value = order.total_price - amount_paid

    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        formset = OrderItemFormSet(request.POST, queryset=order_items)
        transaction_form = TransactionForm(request.POST)
        amount = int(request.POST.get('amount'))
        if form.is_valid() and formset.is_valid() and transaction_form.is_valid():
            order = form.save()
            instances = formset.save(commit=False)
            for instance in instances:
                instance.order = order
                instance.save()
            if amount > 0:
                transaction = transaction_form.save(commit=False)
                transaction.tailor = request.user
                transaction.order = order
                transaction.save()
            return redirect('/orders')
        else:
            print(transaction_form.errors,form.errors,formset.errors)
    else:
        form = OrderForm(instance=order)
        formset = OrderItemFormSet(queryset=order_items)
    
    return render(request, 'orders/order_details.html', {
        'form': form, 'formset': formset, 
        'order': order,'transaction_form':transaction_form,
        'amount_paid':amount_paid,
        'max_input_value':max_input_value,
        'title':'Order Details'
        })

@login_required
def filter_orders(request):
    search_query = request.GET.get('search','')
    orders = Order.objects.filter(tailor=request.user)
    if search_query:
        orders = orders.filter(
            Q(customer__first_name__icontains=search_query) |
            Q(id__icontains=search_query)
        )
    paginator = Paginator(orders,5)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    orders_data = list(page_obj.object_list.values('id','total_price', 'items_count', 'customer__first_name'))
    page_data = {
        'number':page_obj.number,
        'num_pages':page_obj.paginator.num_pages,
        'has_next':page_obj.has_next(),
        'has_previous':page_obj.has_previous(),
        'previous_page_number':page_obj.previous_page_number() if page_obj.has_previous() else None,
        'next_page_number':page_obj.next_page_number() if page_obj.has_next() else None,

    }
    return JsonResponse({'page_obj':page_data,'orders':orders_data})

@login_required
def generate_invoice_pdf(request,order_id):
    # Retrieve the order details from the Order model
    order = Order.objects.get(id=order_id)
    order_items = order.items.all()
    transactions = Transaction.objects.filter(order=order)
    amount_paid = 0
    for transaction in transactions:
        amount_paid += transaction.amount

    # Create a BytesIO buffer to write PDF content
    buffer = BytesIO()

    # Create a PDF document
    p = canvas.Canvas(buffer, pagesize=letter)
    p.setFont("Helvetica-Bold", 16)
    p.setTitle(f"{order.customer.first_name}'s Invoice")  # Set PDF title

    # Add invoice details
    logo_path = os.path.join(settings.MEDIA_ROOT,'default','Logo.png')
    print(logo_path)
    p.drawImage(logo_path,220,750,width=60,height=25)
    p.drawString(285, 755, "Invoice Details")
    p.setFont("Helvetica", 12)
    y_coordinate = 710
    p.drawString(50, y_coordinate, f"Invoice Number: {order.id}")
    p.drawString(50, y_coordinate - 20, f"Customer Name: {order.customer.first_name}")
    p.drawString(50, y_coordinate - 40, f"Total Amount: {order.total_price}")
    p.drawString(50, y_coordinate - 60, f"Amount Paid: {amount_paid}")

    # Define the starting y-coordinate for the products
    y_coordinate = 520

    # Loop through each product and its associated photo
    for item in order_items:
        if y_coordinate < 30:
            p.showPage()
            y_coordinate = 620
        image_url = item.product.image.url

        # Decode the URI component
        decoded_url = urllib.parse.unquote(image_url)

        # Remove the '/media' prefix
        correct_url = decoded_url.replace('/media/', '', 1)

        # Add photo to the PDF (replace 'item.image_path' with the actual path to the image file)
        p.drawImage(correct_url, x=50, y=y_coordinate, width=60, height=80)

        # Add item details
        p.drawString(130, y_coordinate + 70, f"item Name: {item.product.title}")
        p.drawString(130, y_coordinate + 50, f"Price: {item.product.price}")
        p.drawString(130, y_coordinate + 30, f"Qty: {item.quantity}")
        p.drawString(130, y_coordinate + 10, f"Status: {item.status}")

        # Increment y-coordinate for the next item
        y_coordinate -= 120  # Adjust this value based on your layout

    # Add more invoice details as needed

    # Save PDF document
    p.showPage()
    p.save()

    # Get PDF content from buffer
    pdf_content = buffer.getvalue()
    buffer.close()

    # Create an HTTP response with PDF content as attachment
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'attachment; filename="invoice_{order.id}.pdf"'
    response.write(pdf_content)

    return response

apps/orders/templates/orders/add_products.html
{%extends 'base.html'%}
{%load static%}

{%block stylesheet%}
<link rel="stylesheet" href="{%static 'css/add_products.css'%}">
{%endblock stylesheet%}

{%block content%}
    <section class=" order-details-section">
        <div class="order-details-container">
            <div class="add-product-form flex gap-3 flex-col">
                <div class="product-name">
                    <label for="">Product Name</label>
                    {{form.item_name}}
                </div>
                <div class="cloth-image flex flex-col gap-2">
                    <label for="">Cloth Image</label>
                    {{form.cloth_image}}
                </div>
                <div class="design-image flex flex-col gap-2">
                    <label for="">Design Image</label>
                    {{form.design_image}}
                </div>
                <div class="unit-price">
                    <label for="">Unit Price</label>
                    {{form.unit_price}}
                </div>
                <div class="quantity flex gap-3">
                    <label for="">Quantity :</label>
                    <span class=" flex gap-2">
                        {{form.quantity}}
                    </span>
                </div>
                <div class="requested-date flex gap-3">
                    <label for="">Requested Pickup Date</label>
                    {{form.requested_date}}
                </div>
            </div>
        </div>
    </section>
{%endblock content%}

apps/orders/templates/orders/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/checkout.css' %}">
{% endblock stylesheet %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{order_form.id.as_hidden}}
        {{ order_form.tailor.as_hidden }}
        {{ order_form.customer.as_hidden }}
        {{ formset.management_form }}
        <input type="hidden" name="checkout" value="true">
        {{ order_form.items_count.as_hidden }}
        <h1 class="text-center text-xl font-medium mt-16">{{ customer.first_name }}'s checkout page </h1>
        <section class="checkout-section min-h-[80vh]">
            <div class="checkout-container flex mx-5 justify-center">
                <div class="master-container my-5 max-w-2xl w-full">
                    <div class="card cart">
                        <label class="title">Your cart</label>
                        <div class="products flex gap-3 my-4">
                            {% for product in selected_products %}
                                <div class="product-container px-5">
                                    <div class="product flex justify-between">
                                        <input type="hidden" name='form-{{ forloop.counter0 }}-product' value="{{ product.id }}">
                                        <div class="flex gap-3">
                                            <img class="h-20 w-16" src="{{ product.image.url }}" alt="">
                                            <div>
                                                <span>{{ product.title | truncatewords:'3' }}</span>
                                                {{ formset.product.as_hidden }}
                                                <p class="w-fit">{{ product.description|truncatewords:'2' }}</p>
                                                <p class="w-fit">No mayo</p>
                                            </div>
                                        </div>
                                        <div class="flex flex-col">
                                            <input class="unit-price" type="hidden" value="{{ product.price }}">
                                            <label class="price small flex">₹{{ product.price }}</label>
                                            <div class="quantity">
                                                <button type="button" class="flex justify-center items-center decrement-button">-</button>
                                                <input readonly  name='form-{{ forloop.counter0 }}-quantity' class="w-8 quantity-input" type="number" value="1">
                                                <button type="button" class="flex justify-center items-center increment-button">+</button>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="text-end text-xs text-gray-600 py-2 flex justify-between sm:my-3 my-2">
                                        <div class="requested_date flex flex-wrap gap-2">
                                            <label class="text-xs sm:text-sm" for="requested_date">Requested Date:</label>
                                            <input class="text-xs sm:text-sm" type="date" name="form-{{ forloop.counter0 }}-requested_date" id="requested_date" required>
                                        </div>
                                        <span onclick="addNotes(event)" class="add-btn border px-2 rounded bg-gray-200 hover:cursor-pointer">+ Add-Notes</span>
                                    </div>
                                    <textarea class="hidden w-full border sm:p-3 p-2 rounded-md sm:text-sm text-xs mb-3" name='form-{{ forloop.counter0 }}-notes' id='notes' rows="2" placeholder="Add notes here..."></textarea>
                                    <div class="is-urgent flex justify-between items-center gap-3 my-3">
                                        <div class="text-xs sm:text-sm">
                                            <label for="id_status">Status</label>
                                            <select class="" name="form-{{forloop.counter0}}-status" id="id_status">
                                                <option value="Not-Stitched">Not-Stitched</option>
                                                <option value="Stitching">Stitching</option>
                                                <option value="Stitched">Stitched</option>
                                                <option value="Delivered">Delivered</option>
                                            </select>
                                        </div>
                                        <div class="flex items-center justify-center gap-2">
                                            <span class="sm:text-sm text-xs">Urgent:</span>
                                            <label onclick="toggleUrgent(event)" class="toggle-switch">
                                                <input class="urgent-checkbox" name='form-{{ forloop.counter0 }}-urgent' type="checkbox">
                                                <div class="toggle-switch-background">
                                                    <div class="toggle-switch-handle"></div>
                                                </div>
                                            </label>
                                        </div>
                                    </div>
                                    {% if not forloop.last %} <hr class="my-3"> {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="card checkout mb-5">
                        <label class="title">Checkout</label>
                        <div class="details">
                            <span>Your cart subtotal:</span>
                            <span class="sub-total"></span>
                            <span>Payment Type</span>
                            <span>{{ order_form.payment_type }}</span>
                            <span class="advance hidden">Add Advance</span>
                            <span class="advance hidden"><input required type="number" name="amount" value="0" step="any" id="id_amount"></span>
                        </div>
                        <div class="checkout--footer">
                            <label class="final-price text-xl font-medium"><sup>₹</sup>57.99</label>
                            {{ order_form.total_price.as_hidden }}
                            <button type="submit" class="checkout-btn">Create Order</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
    <script src="{% static 'js/checkout.js' %}"></script>
{% endblock content %}

apps/orders/templates/orders/order_details.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'css/order_details.css' %}">
{% endblock stylesheet %}

{%block title%}
    {{title}}
{%endblock title%}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form.id.as_hidden}}
        {{ form.tailor.as_hidden }}
        {{ form.customer.as_hidden }}
        {{ form.items_count.as_hidden }}
        {{formset.management_form}}
        
        <h1 class="text-center text-xl font-medium mt-16">{{ form.instance.customer.first_name }}'s Order details page <a class="  border py-2 px-4 bg-yellow-200 text-sm ml-5 rounded-lg" href="/generate-invoice-pdf/{{order.id}}">Download Invoice</a></h1>
        <section class="checkout-section min-h-[80vh]">
            <div class="checkout-container flex mx-5 justify-center">
                <div class="master-container my-5 max-w-2xl w-full">
                    <div class="card cart">
                        <label class="title">Your cart</label>
                        <div class="products flex gap-3 my-4">
                            {% for order_form in formset %}
                                <div class="product-container px-5">
                                    <div class="product flex justify-between">
                                        {{ order_form.product.as_hidden }}
                                        {{ order_form.status.as_hidden }}
                                        {{order_form.id.as_hidden}}
                                        

                                        <div class="flex gap-3">
                                            <img class="h-20 w-16" src="{{ order_form.instance.product.image.url }}" alt="">
                                            <div>
                                                <span>{{ order_form.instance.product.title | truncatewords:'2' }}</span>
                                                <p class="w-fit">{{ order_form.instance.product.description|truncatewords:'2' }}</p>
                                                <p class="w-fit">No mayo</p>
                                            </div>
                                        </div>

                                        <div class="flex flex-col">
                                            <input class="unit-price" type="hidden" value="{{ order_form.instance.product.price }}">
                                            <label class="price small flex"></label>
                                            {%if form.instance.payment_type == 'PRE'%} 
                                                <div class="flex content-center">Qty: {{order_form.instance.quantity}}</div>
                                                <button type="button" class="justify-center items-center decrement-button hidden">-</button>
                                                <input readonly  name="{{order_form.prefix}}-quantity" class="w-8 quantity-input hidden" type="number" value="{{ order_form.instance.quantity }}">
                                                <button type="button" class=" justify-center items-center increment-button hidden">+</button>
                                            {%else%}
                                            <div class="quantity">
                                                <button type="button" class="flex justify-center items-center decrement-button">-</button>
                                                <input readonly  name="{{order_form.prefix}}-quantity" class="w-8 quantity-input" type="number" value="{{ order_form.instance.quantity }}">
                                                <button type="button" class="flex justify-center items-center increment-button">+</button>
                                            </div>
                                            {%endif%}
                                        </div>
                                    </div>

                                    <div class="text-end text-xs text-gray-600 py-2 flex justify-between sm:my-3 my-2">
                                      <div class="requested_date flex flex-wrap gap-2">
                                          <label class="text-xs sm:text-sm" for="requested_date">Req. Date:</label>
                                          <input value="{{order_form.requested_date.value| date:'Y-m-d'}}"  class="text-xs sm:text-sm" type="date" name="{{order_form.prefix}}-requested_date" id="requested_date" required>
                                      </div>
                                      <span onclick="addNotes(event)" class="add-btn border px-2 rounded bg-gray-200 hover:cursor-pointer"> Notes</span>
                                    </div>
                                    <textarea class="hidden w-full border sm:p-3 p-2 rounded-md sm:text-sm text-xs mb-3" name='order_form-{{ forloop.counter0 }}-notes' id='notes' rows="2" placeholder="Add notes here...">{{order_form.notes.value}}</textarea>
                                    <div class="is-urgent flex justify-between items-center gap-3 my-3">
                                      <div class="text-xs sm:text-sm">
                                        <label for="">Status</label>
                                        {{order_form.status}}
                                      </div>
                                      <div class="flex items-center justify-center gap-2">
                                        <span class="sm:text-sm text-xs">Urgent:</span>
                                        <label onclick="toggleUrgent(event)" class="toggle-switch">
                                          <input class="urgent-checkbox" name="{{ order_form.prefix }}-urgent" {%if order_form.urgent.value%} checked {%endif%} type="checkbox">
                                            <div class="toggle-switch-background">
                                                <div class="toggle-switch-handle"></div>
                                            </div>
                                        </label>
                                      </div>
                                    </div>
                                  {% if not forloop.last %} <hr class="my-3"> {% endif %}
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="card checkout mb-5">
                        <label class="title">Checkout</label>
                        <div class="details">
                            <span>Payment Type</span>
                            <span>{{ form.instance.payment_type }}PAID{{form.payment_type.as_hidden}}</span>
                            <span>Your Order subtotal:</span>
                            <span class="sub-total">{{form.instance.total_price}}</span>
                            {%if form.instance.payment_type == 'POST'%}
                                <span>Amount Paid</span>
                                <span>{{ amount_paid }}</span>
                                <!-- <span>Due</span>
                                <span>{{transaction_form.amount}}</span> -->
                                {%if amount_paid < form.instance.total_price%}
                                    <span>Add Amount</span>
                                    <span><input required type="number" min="1" max="{{max_input_value}}" name="amount" id="id_amount" value="0"></span>
                                {%endif%}
                            {%else%}
                                <input  type="hidden" min="1" max="{{max_input_value}}" name="amount" id="id_amount" value="0">
                            {%endif%}
                        </div>

                        <div class="checkout--footer rounded-md">
                            <label class="final-price text-xl font-medium"><sup>₹</sup>{{form.instance.total_price}}</label>
                            {{form.total_price.as_hidden}}
                            <button type="submit" class="update-btn">Update Order</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </form>
    <script src="{% static 'js/order_details.js' %}"></script>
{% endblock content %}