TailorFlow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.home.urls')),
    path('',include('apps.tailors.urls')),
    path('',include('apps.customers.urls')),
    path('',include('apps.orders.urls')),
    path('',include('apps.products.urls')),
    path('',include('apps.dashboard.urls')),
    path('',include('apps.transactions.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

apps/customers/urls.py
from django.shortcuts import render
from django.urls import path, include
from . import views

# Create your views here.

urlpatterns = [
    path('new-customer/',views.new_customer,name='new-customer'),
    path('customers/',views.customers,name='customers'),
    path('add-measurements/<int:customer_id>/',views.add_measurements,name='add-measurements'),
    path('edit-customer/<int:customer_id>/',views.edit_customer,name='edit-customer'),
    path('customer-details/<int:customer_id>/',views.customer_details,name="customer-details"),
    path('edit-measurements/<int:customer_id>/',views.edit_measurements,name='edit-measurements'),
    path('api/filter-customers/',views.filter_customers,name='filter-customers')
] 

apps/customers/models.py
from django.db import models
from apps.tailors.models import TailorUser
from django.dispatch import receiver
from django.db.models.signals import pre_delete
import os
from django.conf import settings
# from orders.models import Order
# from transactions.models import Transaction
# Create your models here. 

class Customer(models.Model):
    gender_choices = [
        ('M',"Male"),
        ('F',"Female"),
    ]
    tailor = models.ForeignKey(TailorUser,on_delete=models.CASCADE,blank=True)
    # orders = models.ForeignKey(Order,on_delete=models.CASCADE,null=True)
    # transactions = models.ForeignKey(Transaction,on_delete=models.CASCADE,null=True)
    first_name = models.CharField(max_length=100,blank=False)
    last_name = models.CharField(max_length = 100)
    email = models.EmailField(blank=False)
    gender = models.CharField(max_length=1,choices=gender_choices)
    city = models.CharField(max_length=50,blank=False)
    phone = models.CharField(max_length=20,blank=False)
    profile = models.ImageField(blank=True,null=True,upload_to='profile/',default='default/profile-user.png')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-id']

    def __str__(self) -> str:
        return self.first_name
    
@receiver(pre_delete,sender=Customer)
def delete_profile_images(sender,instance,*args, **kwargs):
    image_path = instance.profile.path
    if instance.profile and image_path != os.path.join(settings.BASE_DIR, 'media', 'default', 'profile-user.png'):
        if os.path.exists(image_path):
            os.remove(image_path)
                


class Measurements(models.Model):
    customer = models.OneToOneField(
        Customer, on_delete=models.CASCADE, primary_key=True)
    neck = models.FloatField(null=True, blank=True,default=0)
    chest = models.FloatField(null=True, blank=True,default=0)
    waist = models.FloatField(null=True, blank=True,default=0)
    hips = models.FloatField(null=True, blank=True,default=0)
    thigh = models.FloatField(null=True, blank=True,default=0)
    knee = models.FloatField(null=True, blank=True,default=0)
    calf = models.FloatField(null=True, blank=True,default=0)
    sleeve = models.FloatField(null=True, blank=True,default=0)
    back = models.FloatField(null=True, blank=True,default=0)
    waistband = models.FloatField(null=True, blank=True,default=0)
    outseam = models.FloatField(null=True, blank=True,default=0)
    inseam = models.FloatField(null=True, blank=True,default=0)
    ankle = models.FloatField(null=True, blank=True,default=0)

    def __str__(self) -> str:
        return self.customer.first_name

apps/customers/forms.py
from django import forms
from .models import Customer, Measurements

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = "__all__"

class MeasurementsForm(forms.ModelForm):
    class Meta:
        model = Measurements
        fields = "__all__"

apps/customers/views.py
from django.shortcuts import render, redirect
from .forms import CustomerForm,MeasurementsForm
from django.db import IntegrityError
from .models import Customer, Measurements
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from django.conf import settings
from django.core.paginator import Paginator

@login_required
def new_customer(request):
    # origin = request.GET.get('origin','')
    form = CustomerForm() 

    if request.method == "POST":
        form = CustomerForm(request.POST, request.FILES)

        if form.is_valid():
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            if Customer.objects.filter(tailor=request.user).filter(phone=phone):
                form.add_error('phone','Customer with this phone already exists')
            if Customer.objects.filter(tailor=request.user).filter(email=email):
                form.add_error('email','Customer with this email already exists')
            else:
                try:
                    customer = form.save(commit=False)
                    customer.tailor = request.user
                    customer.save()
                    # if origin:
                    #     return redirect(f'/add-measurements/{customer.id}')
                    return redirect(add_measurements,customer_id=customer.id)
                except IntegrityError as e:
                    # Handle any potential IntegrityError that may occur during the save
                    print(e)
                    form.add_error(None, 'A database integrity error occurred.')

    return render(request, 'customers/new_customer.html', context={'form': form})

@login_required
def edit_customer(request,customer_id):
    customer = Customer.objects.get(id=customer_id)
    if request.method == 'POST':
        form = CustomerForm(request.POST,request.FILES,instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.tailor = request.user
            customer.save()
            return redirect(customer_details,customer_id=customer_id)
    else:
        form = CustomerForm(instance=customer)
    return render(request,'customers/edit_customer.html',context={'form':form})

# queryset = Customer.objects.all()
# for obj in queryset:
#     print(obj)

@login_required
def customers(request):
    tailor = request.user
    customers = Customer.objects.filter(tailor=tailor)
    pagination = Paginator(customers,7)
    page_obj = pagination.get_page(1)
    return render(request,'customers/customers.html',context={'page_obj':page_obj,'title':'Customers'})

@login_required
def customer_details(request,customer_id):
    try:
        customer = Customer.objects.get(id=customer_id)
        measurements = Measurements.objects.filter(customer=customer).first()
        form = MeasurementsForm(instance=measurements) if measurements else None
        if request.method == 'POST':
            customer.delete()
            return redirect('/customers')
        return render(request,'customers/customer_details.html',context={'customer':customer,'form':form})
    except Customer.DoesNotExist:
        return HttpResponse('Customer does not exist.')

@login_required
def add_measurements(request,customer_id):
    # next_url = request.GET.get('next','')
    customer = Customer.objects.get(id=customer_id)
    form = MeasurementsForm()
    if request.method == "POST":
        form = MeasurementsForm(request.POST)
        if form.is_valid():
            measurements = form.save(commit=False)
            measurements.customer = customer
            measurements.save()
            # if next_url:
            return redirect('select-products',customer_id=customer_id)
            # return redirect(customer_details,customer_id=customer_id)
    return render(request,'customers/add_measurements.html',context={'form':form,'customer':customer})

@login_required
def edit_measurements(request,customer_id):
    customer = Customer.objects.get(id=customer_id)
    measurements = Measurements.objects.get(customer=customer)
    form = MeasurementsForm(instance=measurements)
    if request.method == "POST":
        form = MeasurementsForm(request.POST,instance=measurements)
        if form.is_valid():
            form.save()
            return redirect(customer_details,customer_id=customer_id)
    return render(request,'customers/edit_measurements.html',context={'customer':customer,'form':form})

@login_required
def filter_customers(request):
    search = request.GET.get('search','')
    gender = request.GET.get('gender','')
    sortby = request.GET.get('sortby','')

    customers = Customer.objects.filter(tailor=request.user)

    if search:
        customers = customers.filter(
            Q(first_name__icontains=search) |
            Q(last_name__icontains=search) |
            Q(email__icontains=search) |
            Q(city__icontains=search) |
            Q(phone__icontains=search)
        ).distinct()
    
    if gender:
        customers = customers.filter(gender = gender)
    
    if sortby:
        customers = customers.order_by(sortby)
    
    pagination = Paginator(customers,7)
    page_num = request.GET.get('page')
    page_obj = pagination.get_page(page_num)
    page_data = {
        'number':page_obj.number,
        'num_pages':page_obj.paginator.num_pages,
        'has_next':page_obj.has_next(),
        'has_previous':page_obj.has_previous(),
        'previous_page_number':page_obj.previous_page_number() if page_obj.has_previous() else None,
        'next_page_number':page_obj.next_page_number() if page_obj.has_next() else None,

    }
    customers_data = list(page_obj.object_list.values())
    for customer in customers_data:
        customer['profile'] = settings.MEDIA_URL + str(customer['profile'])
    return JsonResponse({'customers':customers_data,'page_obj':page_data})

apps/customers/templates/customers/addMeasurements.html
{%extends 'base.html'%}
{%load static%}
{%block title%} Add Measurements {%endblock title%}
{%block stylesheet%} <link rel="stylesheet" href="{% static 'css/addMeasurements.css'%}"> {%endblock stylesheet%}
{%block content%}


{%endblock content%}

apps/customers/templates/customers/add_measurements.html
{%extends 'base.html'%}
{% load custom_filters %}
{%load static%}
{%block title%} Add Measurements {%endblock title%}
{%block stylesheet%} <link rel="stylesheet" href="{% static 'css/add_measurements.css'%}"> {%endblock stylesheet%}
{%block content%}
<form action="" method="post">
    {%csrf_token%}
    <section class="measurements-section w-full ">
        <h1 class=" p-5 text-xl font-medium text-center">Add {{customer.first_name}}'s measurements</h1>

        {%include 'customers/measurements_form.html' with measurements_content='measurements_content'%}
        
        <div class=" flex justify-center items-center pb-7 ">
            <button type="submit" class="submit-btn bg-yellow-400 px-3 rounded-md hover:bg-yellow-300">Submit</button>
        </div>
    </section>
    <script>
        function confirmBeforeUnload(event) {
            event.returnValue = 'are you sure?';
        }
        window.addEventListener('beforeunload',confirmBeforeUnload)
        const submitBtn = document.querySelector('.submit-btn')
        console.log(submitBtn)
        submitBtn.addEventListener('click',()=>window.removeEventListener('beforeunload',confirmBeforeUnload))
    </script>
</form>
{%endblock content%}

apps/customers/templates/customers/customer_form.html
<div class=" mb-4">
    <input name="first_name" id="id_first_name" {%if form.first_name.value and not form.first_name.errors%} value="{{form.first_name.value}}" {%endif%} placeholder="First Name" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" type="text">
    <span class=" text-red-400">{{form.first_name.errors}}</span>
</div>
<div class=" mb-4">
    <input name="last_name" id="id_last_name" {%if form.first_name.value and not form.last_name.errors%} value="{{form.last_name.value}}" {%endif%} placeholder="Last Name" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" type="text">
    <span class=" text-red-400">{{form.last_name.errors}}</span>
</div>

<div class=" mb-4">
    <input name="email" id="id_email" {%if form.email.value and not form.email.errors%} value="{{form.email.value}}" {%endif%} placeholder="Email" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" type="email">
    <span class=" text-red-400">{{form.email.errors}}</span>
</div>

<div class=" mb-4">
    <input name="phone" id="id_phone" {%if form.phone.value and not form.phone.errors%} value="{{form.phone.value}}" {%endif%} placeholder="Phone" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" type="text">
    <span class=" text-red-400">{{form.phone.errors}}</span>
</div>
<div class=" mb-4">
    <input name="city" id="id_city" {%if form.city.value and not form.city.errors%} value="{{form.city.value}}" {%endif%} placeholder="City" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" type="text">
    <span class=" text-red-400">{{form.email.errors}}</span>
</div>

<div class="">
    <select name="gender" id="id_gender" class=" w-full bg-gray-100 text-gray-900 border-0 rounded-md p-2 mb-4 focus:bg-gray-200 focus:outline-none focus:ring-1 focus:ring-blue-500 transition ease-in-out duration-150" id="gender">
        <option {% if form.gender.value == 'M'%} selected {%endif%} value="M">Male</option>
        <option {% if form.gender.value == 'F'%} selected {%endif%} value="F">Female</option>
    </select>
</div>

<div class="custom-file-container bg-gray-100 rounded-md w-full">
    <label for="id_profile" id="custom-file-label" class="custom-file-label text-black">{%if profile.value%} {{profile.name}} {%else%} Profile {%endif%}</label>
    <input type="file" id="id_profile" name="profile" class="custom-file-input" onchange="updateLabel()">
    <span class=" text-red-400">{{form.profile.errors}}</span>
</div>                  

<script>
    function updateLabel() {
        const fileInput = document.getElementById('id_profile');
        const fileLabel = document.getElementById('custom-file-label');
        
        if (fileInput.files.length > 0) {
          fileLabel.textContent = fileInput.files[0].name;
        } else {
          fileLabel.textContent = 'Drop Profile';
        }
      }
      
</script>

apps/customers/templates/customers/measurements_form.html
{%load static%}
{% block measurements_content%}

<input type="hidden" name="customer" value={{customer.id}}>
<div class="measurements-content p-10  sm:pt-5  sm:flex mx-auto sm:justify-center sm:items-center">
    {% if customer.gender == 'F'%}
        <div class="left-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full   sm:h-[30rem] sm:min-w-[140px] sm:flex flex-col sm:items-end">
            <p class="neck input-field flex sm:block justify-between sm:justify-normal  sm:mt-8">
                <label for="id_neck">Neck - </label>
                {{form.neck}}
            </p>
            <p class="chest mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_chest">Chest - </label>
                {{form.chest}}
            </p>
            <p class="waist mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_waist">Waist - </label>
                {{form.waist}}
            </p>
            <p class="hips mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-6">
                <label for="id_hips">Hips - </label>
                {{form.hips}}
            </p>
            <p class="thigh mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_thigh">Thigh - </label>
                {{form.thigh}}
            </p>
            <p class="knee mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-5">
                <label for="id_knee">Knee - </label>
                {{form.knee}}
            </p>
            <p class="calf mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-8">
                <label for="id_calf">Calf - </label>
                {{form.calf}}
            </p>
        </div>


        <div class="img-container hidden sm:block  sm:min-w-[275px] sm:w-[80%] sm:max-w-[400px]">
            <img class=" sm:h-[30rem] sm:w-full" src="{%static 'images/women_body_measurements.jpeg'%}" alt="" /> 
        </div>


        <div class="right-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full sm:min-w-[180px] sm:h-[30rem] sm:flex flex-col items-stretch">
            <p class="sleeve mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_sleeve">sleeve - </label>
                {{form.sleeve}}
            </p>
            <p class="back mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-14">
                <label for="id_back">back - </label>
                {{form.back}}
            </p>
            <p class="waistband mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-4">
                <label for="id_waistband">waistband - </label>
                {{form.waistband}}
            </p>
            <p class="outseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-20">
                <label for="id_outseam">outseam - </label>
                {{form.outseam}}
            </p>
            <p class="inseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_inseam">inseam - </label>
                {{form.inseam}}
            </p>
            <p class="ankle mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_ankle">ankle - </label>
                {{form.ankle}}
            </p>
        </div>

    {%else%}

        <div class="left-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full   sm:h-[30rem] sm:min-w-[140px] sm:flex flex-col sm:items-end">
            <p class="neck input-field flex sm:block justify-between sm:justify-normal  sm:mt-12">
                <label for="id_neck">Neck - </label>
                {{form.neck}}
            </p>
            <p class="chest mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_chest">Chest - </label>
                {{form.chest}}
            </p>
            <p class="waist mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_waist">Waist - </label>
                {{form.waist}}
            </p>
            <p class="hips mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-6">
                <label for="id_hips">Hips - </label>
                {{form.hips}}
            </p>
            <p class="knee mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-5">
                <label for="id_knee">Knee - </label>
                {{form.knee}}
            </p>
            <p class="thigh mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-4">
                <label for="id_thigh">Thigh - </label>
                {{form.thigh}}
            </p>
            <p class="calf mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-8">
                <label for="id_calf">Calf - </label>
                {{form.calf}}
            </p>
        </div>


        <div class="img-container hidden sm:block  sm:min-w-[275px] sm:w-[80%] sm:max-w-[400px]">   
            <img class=" sm:h-[30rem] sm:w-full" src="{%static 'images/men_body_measurements1.jpeg'%}" alt="" />
        </div>

        
        <div class="right-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full sm:min-w-[180px] sm:h-[30rem] sm:flex flex-col items-stretch">
            <p class="sleeve mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_sleeve">sleeve - </label>
                {{form.sleeve}}
            </p>
            <p class="back mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_back">back - </label>
                {{form.back}}
            </p>
            <p class="waistband mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-10">
                <label for="id_waistband">waistband - </label>
                {{form.waistband}}
            </p>
            <p class="outseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_outseam">outseam - </label>
                {{form.outseam}}
            </p>
            <p class="inseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_inseam">inseam - </label>
                {{form.inseam}}
            </p>
            <p class="ankle mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_ankle">ankle - </label>
                {{form.ankle}}
            </p>
        </div>
    {%endif%} 
</div>

{%endblock measurements_content%}

apps/customers/templates/customers/view_measurements.html
{%load static%}
{% block measurements_content%}
<div class="measurements-content p-10  sm:pt-5  sm:flex mx-auto sm:justify-center sm:items-center">
    {% if customer.gender == 'F'%}
        <div class="left-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full   sm:h-[30rem] sm:min-w-[140px] sm:flex flex-col sm:items-end">
            <p class="neck input-field flex sm:block justify-between sm:justify-normal  sm:mt-8">
                <label for="id_neck">Neck - </label>
                {{form.neck.value}}
            </p>
            <p class="chest mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_chest">Chest - </label>
                {{form.chest.value}}
            </p>
            <p class="waist mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_waist">Waist - </label>
                {{form.waist.value}}
            </p>
            <p class="hips mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-6">
                <label for="id_hips">Hips - </label>
                {{form.hips.value}}
            </p>
            <p class="thigh mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_thigh">Thigh - </label>
                {{form.thigh.value}}
            </p>
            <p class="knee mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-5">
                <label for="id_knee">Knee - </label>
                {{form.knee.value}}
            </p>
            <p class="calf mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-8">
                <label for="id_calf">Calf - </label>
                {{form.calf.value}}
            </p>
        </div>


        <div class="img-container hidden sm:block  sm:min-w-[275px] sm:w-[80%] sm:max-w-[400px]">
            <img class=" sm:h-[30rem] sm:w-full" src="{%static 'images/women_body_measurements.jpeg'%}" alt="" /> 
        </div>


        <div class="right-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full sm:min-w-[180px] sm:h-[30rem] sm:flex flex-col items-stretch">
            <p class="sleeve mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_sleeve">sleeve - </label>
                {{form.sleeve.value}}
            </p>
            <p class="back mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-14">
                <label for="id_back">back - </label>
                {{form.back.value}}
            </p>
            <p class="waistband mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-4">
                <label for="id_waistband">waistband - </label>
                {{form.waistband.value}}
            </p>
            <p class="outseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-20">
                <label for="id_outseam">outseam - </label>
                {{form.outseam.value}}
            </p>
            <p class="inseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_inseam">inseam - </label>
                {{form.inseam.value}}
            </p>
            <p class="ankle mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_ankle">ankle - </label>
                {{form.ankle.value}}
            </p>
        </div>

    {%else%}

        <div class="left-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full   sm:h-[30rem] sm:min-w-[140px] sm:flex flex-col sm:items-end">
            <p class="neck input-field flex sm:block justify-between sm:justify-normal  sm:mt-12">
                <label for="id_neck">Neck - </label>
                {{form.neck.value}}
            </p>
            <p class="chest mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-7">
                <label for="id_chest">Chest - </label>
                {{form.chest.value}}
            </p>
            <p class="waist mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_waist">Waist - </label>
                {{form.waist.value}}
            </p>
            <p class="hips mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-6">
                <label for="id_hips">Hips - </label>
                {{form.hips.value}}
            </p>
            <p class="knee mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-5">
                <label for="id_knee">Knee - </label>
                {{form.knee.value}}
            </p>
            <p class="thigh mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-4">
                <label for="id_thigh">Thigh - </label>
                {{form.thigh.value}}
            </p>
            <p class="calf mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-8">
                <label for="id_calf">Calf - </label>
                {{form.calf.value}}
            </p>
        </div>


        <div class="img-container hidden sm:block  sm:min-w-[275px] sm:w-[80%] sm:max-w-[400px]">   
            <img class=" sm:h-[30rem] sm:w-full" src="{%static 'images/men_body_measurements1.jpeg'%}" alt="" />
        </div>

        
        <div class="right-measurements max-w-[280px] mx-auto sm:mx-0 sm:max-w-full sm:min-w-[180px] sm:h-[30rem] sm:flex flex-col items-stretch">
            <p class="sleeve mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-9">
                <label for="id_sleeve">sleeve - </label>
                {{form.sleeve.value}}
            </p>
            <p class="back mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_back">back - </label>
                {{form.back.value}}
            </p>
            <p class="waistband mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-10">
                <label for="id_waistband">waistband - </label>
                {{form.waistband.value}}
            </p>
            <p class="outseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-12">
                <label for="id_outseam">outseam - </label>
                {{form.outseam.value}}
            </p>
            <p class="inseam mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_inseam">inseam - </label>
                {{form.inseam.value}}
            </p>
            <p class="ankle mt-2 input-field flex sm:block  justify-between sm:justify-normal sm:mt-11">
                <label for="id_ankle">ankle - </label>
                {{form.ankle.value}}
            </p>
        </div>
    {%endif%} 
</div>

{%endblock measurements_content%}